version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: support_bot
    restart: always
    environment:
      POSTGRES_DB: postgres_support_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
